/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is the server up?
         * @description Deliberately says nothing about the cell -- that is what ``/v1/preflight`` is for.
         *
         *     A health check that reports on hardware turns "the server is running" and "the robot is ready"
         *     into one answer, and then a green light means neither reliably.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is this cell runnable? */
        get: operations["get_preflight_v1_preflight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config/writable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What may be set from here
         * @description The guided-write form, described by the library rather than duplicated in the frontend.
         *
         *     The ``measure`` text is what the operator needs and what a type annotation cannot give them: not
         *     "float, kg" but *weigh the whole assembly including the coupling plate and the hoses*.
         */
        get: operations["get_writable_v1_config_writable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A value and where it came from */
        get: operations["get_explain_v1_config_explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Write measured values (all or none)
         * @description Write a group of measurements as one transaction.
         *
         *     A group, not a key, because the schema has cross-field rules that no single write can satisfy: a
         *     tool frame that declares an owner while its transform is still identity is rejected, so the three
         *     tool-frame keys only ever validate together.
         */
        patch: operations["patch_config_v1_config_patch"];
        trace?: never;
    };
    "/v1/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where is the cell? */
        get: operations["get_cell_v1_cell_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cell/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assemble the cell (no robot is touched)
         * @description Build through the same path the CLI runner uses -- literally the same functions.
         *
         *     ``rehearse=true`` builds the desk scene instead of opening a camera and loading models, which is how
         *     the whole console stays playable with no hardware attached. Not cheap otherwise: a real build takes
         *     tens of seconds while the detector and segmenter load onto the GPU.
         */
        post: operations["post_build_v1_cell_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cell/connect-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What will move, and the token that acknowledges it */
        get: operations["get_connect_preview_v1_cell_connect_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cell/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bring the cell up (THIS MOVES)
         * @description Arm first, then gripper, and roll the arm back if the gripper refuses.
         *
         *     The cross-process lock is taken BEFORE the arm, so a cell already owned by the CLI runner is
         *     refused without a single command reaching the controller.
         */
        post: operations["post_connect_v1_cell_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cell/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live telemetry (receive stream only)
         * @description A snapshot cheap enough to poll.
         *
         *     The default reading is the RTDE **output stream** -- pose, joints, TCP wrench -- which the controller
         *     is already broadcasting, so polling it costs a running motion nothing. Two neighbouring reads are
         *     deliberately absent: ``get_joint_torques`` goes through the control interface a pick is using, and it
         *     is never offered here.
         *
         *     ``include_controller_state=true`` adds robot mode, safety mode and the human-readable safety text --
         *     and costs a **dashboard socket round trip per call**, which is why it is opt-in rather than part of
         *     the default tick. Poll it at seconds, not at frames.
         *
         *     Read-only in the strong sense: there is no counterpart that clears a protective stop. That is done
         *     where the arm is visible, at the pendant, for the same reason there is no E-stop button here.
         */
        get: operations["get_status_v1_cell_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cell/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take the cell down
         * @description Gripper first, then arm -- the reverse of connect, so a cup's release still reaches the I/O.
         *
         *     Idempotent: disconnecting an already-disconnected cell is a no-op rather than an error, because the
         *     one thing an operator must always be able to do is put the cell down.
         */
        post: operations["post_disconnect_v1_cell_disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/diagnostics/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Which route a prompt would take -- no GPU, no model, no image
         * @description Answer 'why was that pick slow / why was it refused' by typing the prompt instead of running it.
         *
         *     Pure text analysis, so it costs nothing and works on a cell with no weights at all. It also reports
         *     whether the chosen route could actually RUN here, which is the difference between "the router would
         *     send this to the VLM" and "this pick will work".
         */
        get: operations["preview_route_v1_diagnostics_route_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything that can be checked without moving
         * @description One call, because an operator at a bench wants one panel, not three requests.
         *
         *     Ordered the way the runbook is: software first (free), then the planner (free), then the network
         *     (cheap). Each stage's failure explains the next stage's failure, which is the whole reason the
         *     runbook has an order.
         */
        get: operations["get_diagnostics_v1_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a run (THIS MOVES)
         * @description 202, not 200: the work is accepted and happening elsewhere, not finished when this returns.
         */
        post: operations["post_pick_v1_pick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pick/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Do not start the next attempt
         * @description Stop, in the only sense this process can honour.
         *
         *     The flag is read by the pick loop before it begins the next attempt, so a motion already in flight
         *     completes. There is deliberately nothing stronger here: a stop that travels over a socket depends on
         *     latency, an open tab and an awake laptop, and the one that does not is the button on the wall.
         */
        post: operations["post_stop_v1_pick_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent runs, newest first */
        get: operations["get_runs_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/camera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the cell is looking at
         * @description One picture and one sentence saying what the picture IS.
         *
         *     Polled rather than streamed, on purpose. A socket would have to decide what "no picture" looks like
         *     between frames, and every one of the four no-picture states here is a state an operator needs to
         *     READ, not to infer from a stalled image. A poll makes each tick a complete, self-describing answer:
         *     a cell that has not been built, a pick that owns the camera, a simulated source that cannot be
         *     peeked at, or a frame.
         *
         *     **Declared ``def``, not ``async def``, and that is load-bearing.** A real ``grab()`` blocks on
         *     ``wait_for_frames``; FastAPI runs a synchronous route in its threadpool, so the block lands there
         *     instead of on the event loop. An ``async def`` here would stall the run event stream every tick --
         *     the one thing on this server that must not pause while a robot is moving.
         *
         *     The JPEG quality comes from ``runtime.image_encoding.frame_quality``, which has been in the config
         *     schema (documented as "quality used for streamed ... preview images") with no reader since before
         *     this endpoint existed.
         */
        get: operations["get_camera_v1_camera_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/overlay/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start rendering the debug overlay
         * @description Opt into the overlay render. Off by default, in the library, and it costs real time per pick.
         *
         *     The calculator only forwards the camera's RGB into the renderer when this is on, which is what keeps
         *     the default pick path free of it. Turning it on is therefore a deliberate trade: a picture per
         *     segmentation, paid for out of the pick's own latency budget.
         */
        post: operations["post_overlay_enable_v1_overlay_enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voice/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Speech to a prompt
         * @description Turn a recording into text. It returns the TEXT; it does not start anything.
         *
         *     Deliberately not a shortcut to a pick. A spoken command that went straight to motion would mean a
         *     misheard word moves an arm, so speech lands in the prompt box and a human presses the button -- the
         *     same button, with the same acknowledgement, as a typed prompt.
         *
         *     Whisper is an optional dependency and it is loaded on first use, not at import: a console on a
         *     machine without it must still start, and must say what is missing rather than fail to boot.
         */
        post: operations["post_transcribe_v1_voice_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * KPIs over the logged records
         * @description Rolled up with the SAME function the offline gate uses.
         *
         *     A console that computed its own success rate would eventually disagree with
         *     ``python -m backend.src.robot.grasping.replay --records``, and then nobody could say which number
         *     was real.
         */
        get: operations["get_kpis_v1_history_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logged grasp attempts, newest first */
        get: operations["get_records_v1_history_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/runs.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs as CSV
         * @description One row per run: the report-level view, for someone writing up a bring-up day.
         */
        get: operations["get_runs_csv_v1_history_runs_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/records.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grasp attempts as CSV
         * @description One row per ATTEMPT: the analysis view.
         *
         *     Only the blocks the serializer actually populates get columns. An empty ``selected_grasp`` column on
         *     every row would suggest the data exists and happened to be missing, rather than that it is never
         *     written on the live path.
         */
        get: operations["get_records_csv_v1_history_records_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This session's runs (in memory)
         * @description The rich view, and the perishable one: these live in memory and go when the server does.
         */
        get: operations["get_session_runs_v1_history_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_post_transcribe_v1_voice_transcribe_post */
        Body_post_transcribe_v1_voice_transcribe_post: {
            /**
             * Audio
             * Format: binary
             * @description WAV/FLAC/OGG audio to transcribe
             */
            audio: string;
        };
        /**
         * CellOut
         * @description Where the cell is, what it is made of, and who owns it.
         */
        CellOut: {
            /** State */
            state: string;
            /** Arm */
            arm?: string | null;
            /** Gripper */
            gripper?: string | null;
            /** Vendor */
            vendor: string;
            /** Profile */
            profile?: string | null;
            /** Gripper Substitution */
            gripper_substitution?: {
                [key: string]: unknown;
            } | null;
            /** Lock Key */
            lock_key?: string | null;
            /** Lock Holder */
            lock_holder?: string | null;
            /** Active Run Id */
            active_run_id?: string | null;
            perception?: components["schemas"]["PerceptionStackOut"] | null;
        };
        /**
         * ConfigPatchOut
         * @description The result of a guided write. All the values landed, or the request failed and none did.
         */
        ConfigPatchOut: {
            /** Applied */
            applied: boolean;
            /** Values */
            values: {
                [key: string]: unknown;
            };
            /** Files */
            files: string[];
            preflight: components["schemas"]["PreflightOut"];
        };
        /**
         * ConfigValueOut
         * @description A config key with the provenance the CLI's ``explain`` prints.
         *
         *     ``source`` and ``layers`` are what make this worth an endpoint at all: with layered profiles, "what
         *     is the value" is only half a question -- the other half is which layer won, and the UI must be able
         *     to say so without the operator reconstructing a four-file merge in their head.
         */
        ConfigValueOut: {
            /** Key */
            key: string;
            /** Value */
            value: unknown;
            /** Type */
            type?: string | null;
            /** Default */
            default?: unknown;
            /** Doc */
            doc?: string | null;
            /** Doc Scope */
            doc_scope?: string | null;
            /** Source */
            source?: string | null;
            /** Tier */
            tier?: string | null;
            /** Layers */
            layers?: components["schemas"]["LayerOut"][];
            /** Why */
            why?: string | null;
            /**
             * Writable
             * @default false
             */
            writable: boolean;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /**
         * ConnectIn
         * @description The acknowledgement. A token, and nothing else -- there is no force flag.
         */
        ConnectIn: {
            /** Token */
            token: string;
        };
        /**
         * ConnectPreviewOut
         * @description What connecting will do, and the token that records having read it.
         */
        ConnectPreviewOut: {
            /** Token */
            token: string;
            /** Expires At */
            expires_at: string;
            /** Arm */
            arm: string;
            /** Gripper */
            gripper: string;
            /** Warnings */
            warnings?: components["schemas"]["MotionWarningOut"][];
            /** Blocking */
            blocking?: string[];
        };
        /**
         * DiagnosticsOut
         * @description The whole bench panel: software, planner, perception, network. Nothing here moves anything.
         */
        DiagnosticsOut: {
            /** Vendors */
            vendors?: components["schemas"]["VendorReadinessOut"][];
            motion_stack: components["schemas"]["MotionStackOut"];
            perception: components["schemas"]["PerceptionStackOut"];
            reachability: components["schemas"]["ReachabilityOut"];
        };
        /**
         * ErrorOut
         * @description One error envelope for every failure, so the client has exactly one shape to handle.
         */
        ErrorOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /**
         * LayerOut
         * @description One file that sets a key: where, what it wrote, and whether it won.
         */
        LayerOut: {
            /** Location */
            location: string;
            /** Raw */
            raw: string;
            /** Winner */
            winner: boolean;
        };
        /**
         * MotionStackOut
         * @description Can this cell plan? Reported for the model the cell is configured to drive, not a default.
         */
        MotionStackOut: {
            /** Model */
            model: string;
            /** Model Source */
            model_source: string;
            /** Fully Anchored */
            fully_anchored: boolean;
            /** Curobo Available */
            curobo_available: boolean;
            /** Curobo Python */
            curobo_python: string;
            /** Curobo Robot Config */
            curobo_robot_config?: string | null;
            /**
             * Curobo Caveat
             * @default
             */
            curobo_caveat: string;
            /** Collision Engine */
            collision_engine?: string | null;
            /**
             * Mesh Bundle Present
             * @default false
             */
            mesh_bundle_present: boolean;
            /** Coal Prefix */
            coal_prefix?: string | null;
        };
        /**
         * MotionWarningOut
         * @description One thing that physically moves when connect is pressed.
         *
         *     Derived from what was BUILT, not from what config asked for: warning about a finger sweep that
         *     cannot happen (because the gripper fell back to a substitute) teaches an operator to skip the
         *     warning that can.
         */
        MotionWarningOut: {
            /** Subject */
            subject: string;
            /** What */
            what: string;
            /** Precaution */
            precaution: string;
        };
        /**
         * PerceptionStackOut
         * @description Which perception stack this cell is configured for, and whether it can actually run.
         *
         *     Answers the question an operator asks before a pick and could not previously ask at all: *which
         *     models will this prompt touch?* The VLM route can be perfectly configured and still unrunnable
         *     because the weights are not on this box -- and until the first complex prompt arrives, nothing says
         *     so. This checks presence WITHOUT loading anything.
         */
        PerceptionStackOut: {
            /**
             * Pipeline Configured
             * @description False = the legacy keys decide everything (the byte-identical default).
             */
            pipeline_configured: boolean;
            /**
             * Kind
             * @description zero_shot | closed_set
             */
            kind: string;
            /**
             * Backend
             * @description grounded_sam | vlm | rtdetr
             */
            backend: string;
            /** Segmenter */
            segmenter: string;
            /**
             * Router Enabled
             * @description True = each prompt is routed between the phrase grounder and the VLM.
             */
            router_enabled: boolean;
            /** Vlm Model Id */
            vlm_model_id?: string | null;
            /**
             * Vlm Weights Present
             * @description Whether the VLM checkpoint is in the local cache. None when no VLM is configured.
             */
            vlm_weights_present?: boolean | null;
            /**
             * Vlm On Unavailable
             * @description refuse = reject the pick | degrade = fall back, loudly.
             */
            vlm_on_unavailable?: string | null;
            /**
             * Detail
             * @description One sentence an operator can act on.
             */
            detail: string;
        };
        /**
         * PickIn
         * @description An operator instruction: what to pick, and how many times.
         */
        PickIn: {
            /**
             * Prompt
             * @default
             */
            prompt: string;
            /**
             * Picks
             * @default 1
             */
            picks: number;
        };
        /**
         * PreflightCheckOut
         * @description One row of the cell checklist, exactly as ``run_config_preflight`` produced it.
         */
        PreflightCheckOut: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "block" | "warn" | "bench";
            /** Detail */
            detail: string;
            /**
             * Fix
             * @default
             */
            fix: string;
        };
        /**
         * PreflightOut
         * @description The whole checklist plus the one-line verdict the operator acts on.
         */
        PreflightOut: {
            /** Checks */
            checks: components["schemas"]["PreflightCheckOut"][];
            /** Ok */
            ok: boolean;
            /** N Blocking */
            n_blocking: number;
            /** N Warn */
            n_warn: number;
            /** N Bench */
            n_bench: number;
            /** Profile */
            profile?: string | null;
            /** Vendor */
            vendor: string;
        };
        /**
         * ReachabilityOut
         * @description Is anything listening at the controller's address?
         */
        ReachabilityOut: {
            /** Checked */
            checked: boolean;
            /** Address */
            address?: string | null;
            /** Port */
            port?: number | null;
            /** Reachable */
            reachable?: boolean | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * RecordOut
         * @description One logged grasp attempt, as the frozen telemetry contract stores it.
         */
        RecordOut: {
            /** Timestamp */
            timestamp: number;
            /** Attempt Id */
            attempt_id: string;
            /** Mode */
            mode: string;
            /** Final Outcome */
            final_outcome: string;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
        };
        /**
         * RollupOut
         * @description KPIs over the logged records, with the unmeasurable ones NAMED rather than zeroed.
         *
         *     ``unmeasurable`` is the load-bearing field. A KPI computed from a value nothing ever writes returns
         *     a confident 0.0, not a blank -- and a 0.0% false-positive-grasp rate on a demo screen is a claim
         *     nobody in this repo has ever been in a position to make.
         */
        RollupOut: {
            /** Total Attempts */
            total_attempts: number;
            /** Kpis */
            kpis?: {
                [key: string]: unknown;
            };
            /** Unmeasurable */
            unmeasurable?: {
                [key: string]: string;
            };
            /** Outcomes */
            outcomes?: {
                [key: string]: number;
            };
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Record Log Path
             * @default
             */
            record_log_path: string;
            /**
             * Record Log Exists
             * @default false
             */
            record_log_exists: boolean;
        };
        /**
         * RoutePreviewOut
         * @description What route a prompt WOULD take -- decided without a GPU, a model, or an image.
         *
         *     The router is pure text analysis, so this is free and instant. It exists because "why was that pick
         *     slow?" and "why did it refuse?" are usually answered by the route, and an operator should be able
         *     to find that out by typing the prompt rather than by running it.
         */
        RoutePreviewOut: {
            /** Prompt */
            prompt: string;
            /**
             * Route
             * @description simple | vlm
             */
            route: string;
            /**
             * Reason
             * @description the rule that decided it, e.g. non_english, negation
             */
            reason: string;
            /**
             * Description
             * @description human-readable, e.g. 'vlm (non_english)'
             */
            description: string;
            /**
             * Normalized Prompt
             * @description What the phrase grounder would actually receive. None on the VLM route, which gets the operator's words untouched.
             */
            normalized_prompt?: string | null;
            /** Signals */
            signals?: {
                [key: string]: unknown;
            };
            /**
             * Runnable
             * @description False when this route is configured but cannot run on this box right now.
             */
            runnable: boolean;
            /** Blocked Reason */
            blocked_reason?: string | null;
        };
        /**
         * RunOut
         * @description One run. The counts are the honest summary; the event stream is the detail.
         */
        RunOut: {
            /** Id */
            id: string;
            /** Prompt */
            prompt: string;
            /** Requested Picks */
            requested_picks: number;
            /** State */
            state: string;
            /** Started At */
            started_at: number;
            /** Finished At */
            finished_at?: number | null;
            /**
             * Succeeded
             * @default 0
             */
            succeeded: number;
            /**
             * Attempted
             * @default 0
             */
            attempted: number;
            /** Outcomes */
            outcomes?: string[];
            /**
             * Error
             * @default
             */
            error: string;
            /**
             * Stop Requested
             * @default false
             */
            stop_requested: boolean;
        };
        /**
         * SdkOut
         * @description One vendor SDK module, as ``doctor`` found it.
         */
        SdkOut: {
            /** Module */
            module: string;
            /** Importable */
            importable: boolean;
            /** Version */
            version?: string | null;
        };
        /**
         * TelemetryOut
         * @description One live snapshot of the cell.
         *
         *     Every measurement is optional because every one comes from an optional capability: sim, dummy and
         *     KUKA advertise no force/torque or controller-status Protocol at all. A missing field means "this
         *     driver does not offer it", which is not an error and does not appear in ``unavailable``.
         */
        TelemetryOut: {
            /** State */
            state: string;
            /** Connected */
            connected: boolean;
            /**
             * Simulated
             * @default false
             */
            simulated: boolean;
            /**
             * Vendor
             * @default
             */
            vendor: string;
            /**
             * Model
             * @default
             */
            model: string;
            /** Tcp Position Mm */
            tcp_position_mm?: number[] | null;
            /** Tcp Quaternion Xyzw */
            tcp_quaternion_xyzw?: number[] | null;
            /** Joint Positions */
            joint_positions?: number[] | null;
            /** Tcp Force N */
            tcp_force_n?: number[] | null;
            /** Tcp Torque Nm */
            tcp_torque_nm?: number[] | null;
            /** Robot Mode */
            robot_mode?: string | null;
            /** Safety Mode */
            safety_mode?: string | null;
            /** Protective Stopped */
            protective_stopped?: boolean | null;
            /** Emergency Stopped */
            emergency_stopped?: boolean | null;
            /** Controller Message */
            controller_message?: string | null;
            /** Controller Is Simulator */
            controller_is_simulator?: boolean | null;
            /** Controller Serial */
            controller_serial?: string | null;
            /** Controller Host */
            controller_host?: string | null;
            /**
             * Controller State Included
             * @default false
             */
            controller_state_included: boolean;
            /** Unavailable */
            unavailable?: {
                [key: string]: string;
            };
        };
        /**
         * TranscriptOut
         * @description What was heard. Text only -- transcription never starts anything on its own.
         */
        TranscriptOut: {
            /** Text */
            text: string;
        };
        /** VendorReadinessOut */
        VendorReadinessOut: {
            /** Vendor */
            vendor: string;
            /** Kind */
            kind: string;
            /** Registered */
            registered: boolean;
            /** Ready */
            ready: boolean;
            /** Note */
            note: string;
            /** Sdks */
            sdks?: components["schemas"]["SdkOut"][];
        };
        /**
         * ViewfinderOut
         * @description What the cell is looking at, and -- always -- WHICH of two pictures this is.
         *
         *     The console can show three things that look alike and mean different things: a colour frame taken
         *     from a device now, a synthetic scene this process drew for a rehearsal, and the grasp overlay the
         *     stack rendered during a pick. Rendering them identically is how a minutes-old segmentation -- or a
         *     picture of a room that does not exist -- ends up on a screen an operator reads as live. So
         *     ``source`` and ``age_s`` travel with every frame and ``human`` says it in words.
         *
         *     ``image_base64`` is ``None`` for the four "no picture" cases, and ``reason`` names which. That is
         *     an answer, not an error: a cell with no camera is a legitimate cell, and a console that returned
         *     404 for it would make an ordinary state look like a fault.
         */
        ViewfinderOut: {
            /** Source */
            source: string;
            /** Reason */
            reason: string;
            /** Human */
            human: string;
            /** Image Base64 */
            image_base64?: string | null;
            /**
             * Media Type
             * @default
             */
            media_type: string;
            /**
             * Width
             * @default 0
             */
            width: number;
            /**
             * Height
             * @default 0
             */
            height: number;
            /** Age S */
            age_s?: number | null;
            /**
             * Age Is Exact
             * @default true
             */
            age_is_exact: boolean;
            /**
             * Overlay Enabled
             * @default false
             */
            overlay_enabled: boolean;
        };
        /**
         * WritableOut
         * @description One key the console offers as a form field, with the instruction for obtaining its value.
         */
        WritableOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Measure */
            measure: string;
            /**
             * Unit
             * @default
             */
            unit: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_preflight_v1_preflight_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreflightOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_writable_v1_config_writable_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritableOut"][];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_explain_v1_config_explain_get: {
        parameters: {
            query: {
                /** @description Dotted config path, e.g. robot.safety.payload.mass_kg */
                key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigValueOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    patch_config_v1_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigPatchOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_cell_v1_cell_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    post_build_v1_cell_build_post: {
        parameters: {
            query?: {
                rehearse?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_connect_preview_v1_cell_connect_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectPreviewOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    post_connect_v1_cell_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_status_v1_cell_status_get: {
        parameters: {
            query?: {
                include_controller_state?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    post_disconnect_v1_cell_disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    preview_route_v1_diagnostics_route_get: {
        parameters: {
            query: {
                prompt: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePreviewOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_diagnostics_v1_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    post_pick_v1_pick_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    post_stop_v1_pick_stop_post: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_runs_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_camera_v1_camera_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewfinderOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    post_overlay_enable_v1_overlay_enable_post: {
        parameters: {
            query?: {
                enabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    post_transcribe_v1_voice_transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_transcribe_v1_voice_transcribe_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_kpis_v1_history_kpis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollupOut"];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_records_v1_history_records_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordOut"][];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_runs_csv_v1_history_runs_csv_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_records_csv_v1_history_records_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_session_runs_v1_history_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description The one failure envelope. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
