/**
 * "What is on the other end of this connection?" — answered in one place, for both pages.
 *
 * There are three distinct states and the console renders three distinct labels. Collapsing any two
 * of them is how a sim result becomes a claim about a factory:
 *
 * | state | shown as | why |
 * |---|---|---|
 * | the DRIVER is a simulator (`simulated`) | *simulated arm* | dummy / Isaac: no controller exists |
 * | the CONTROLLER is provably a simulator (`controller_is_simulator === true`) | *URSim simulator* | real UR software, robot that does not exist |
 * | anything else | *UR controller* — **never "physical"** | this console cannot prove a controller is real, and must not imply it |
 *
 * The third row is the one that takes discipline. `controller_is_simulator` is deliberately
 * three-valued and never `false`: the backend reports `true` only on proof (URSim's `…99999` serial
 * AND a loopback address) and `null` otherwise. `null` means *cannot tell*. A UI that renders it as
 * "physical arm" would be inventing the one fact nobody measured — and it would do so on the page
 * that gets projected in front of investors.
 */

import type { TelemetryOut } from '../api/client'

export type Provenance = {
  kind: 'sim-driver' | 'sim-controller' | 'controller' | 'unknown'
  label: string
  /** `bench` = a simulator; `info` = a real controller stack with no claim about the arm. */
  tone: 'bench' | 'info' | 'idle'
  detail: string
}

export function provenanceOf(t: TelemetryOut | null | undefined): Provenance {
  if (!t || !t.connected) {
    return { kind: 'unknown', label: 'not connected', tone: 'idle', detail: '' }
  }
  const where = [t.vendor, t.model].filter(Boolean).join(' ')
  if (t.simulated) {
    return {
      kind: 'sim-driver',
      label: `simulated arm${where ? ` · ${where}` : ''}`,
      tone: 'bench',
      detail: 'No controller is involved. These numbers are generated by this process.',
    }
  }
  if (t.controller_is_simulator === true) {
    return {
      kind: 'sim-controller',
      label: `simulator · ${where || 'UR'}`,
      tone: 'bench',
      detail:
        `Real controller software (serial ${t.controller_serial ?? '?'} at ` +
        `${t.controller_host ?? '?'}), driving a robot that does not exist. The protocol, the timing ` +
        `and the safety states are genuine; the arm is not.`,
    }
  }
  return {
    kind: 'controller',
    label: `controller · ${where || 'unknown'}`,
    tone: 'info',
    detail:
      'A real controller stack. This console cannot prove whether an arm is bolted to it, so it does ' +
      'not claim one — check the cell.',
  }
}
