/**
 * "What is on the other end of this connection?" — answered in one place, for every page.
 *
 * There are three distinct states and the console renders three distinct labels. Collapsing any two
 * of them is how a sim result becomes a claim about a factory:
 *
 * | state | shown as | why |
 * |---|---|---|
 * | the DRIVER is a simulator (`simulated`) | *simulated arm* | dummy / Isaac: no controller exists |
 * | the CONTROLLER is provably a simulator (`controller_is_simulator === true`) | *URSim simulator* | real UR software, robot that does not exist |
 * | anything else | *UR controller* — **never "physical"** | this console cannot prove a controller is real, and must not imply it |
 *
 * The third row is the one that takes discipline. `controller_is_simulator` is deliberately
 * three-valued and never `false`: the backend reports `true` only on proof (URSim's placeholder serial,
 * `…9999` on a CB3 and `…99999` on an e-Series, AND a loopback address) and `null` otherwise.
 * `null` means *cannot tell*. A UI that renders it as "physical arm" would be inventing the one fact
 * nobody measured — and it would do so on the page that gets projected in front of investors.
 *
 * `label` and `detail` are the rule's own English words (pinned by the screen tests); a screen that speaks the
 * reader's language renders `kind` with `where`, `serial` and `host` through its catalog (`ProvenanceBadge`), and the
 * shell's cell chip reads `kind` alone.
 */

import type { TelemetryOut } from '../api/client'

export type ProvenanceKind = 'sim-driver' | 'sim-controller' | 'controller' | 'unknown'

export type Provenance = {
  kind: ProvenanceKind
  label: string
  /** `bench` = a simulator; `info` = a real controller stack with no claim about the arm. */
  tone: 'bench' | 'info' | 'idle'
  detail: string
  /** The vendor and the model, as the driver names them (`ur ur10`), `''` when it names neither. */
  where: string
  /** The controller's serial and host, where a simulator was proven by them. */
  serial: string | null
  host: string | null
}

export function provenanceOf(t: TelemetryOut | null | undefined): Provenance {
  if (!t || !t.connected) {
    return { kind: 'unknown', label: 'not connected', tone: 'idle', detail: '', where: '', serial: null, host: null }
  }
  const where = [t.vendor, t.model].filter(Boolean).join(' ')
  const serial = t.controller_serial ?? null
  const host = t.controller_host ?? null
  if (t.simulated) {
    return {
      kind: 'sim-driver',
      label: `simulated arm${where ? ` · ${where}` : ''}`,
      tone: 'bench',
      detail: 'No controller is involved. These numbers are generated by this process.',
      where,
      serial,
      host,
    }
  }
  if (t.controller_is_simulator === true) {
    return {
      kind: 'sim-controller',
      label: `simulator · ${where || 'UR'}`,
      tone: 'bench',
      detail:
        `Real controller software (serial ${serial ?? '?'} at ` +
        `${host ?? '?'}), driving a robot that does not exist. The protocol, the timing ` +
        `and the safety states are genuine; the arm is not.`,
      where,
      serial,
      host,
    }
  }
  return {
    kind: 'controller',
    label: `controller · ${where || 'unknown'}`,
    tone: 'info',
    detail:
      'A real controller stack. This console cannot prove whether an arm is bolted to it, so it does ' +
      'not claim one — check the cell.',
    where,
    serial,
    host,
  }
}
